version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: consulat_db
    environment:
      POSTGRES_USER: okafrancois
      POSTGRES_PASSWORD: ok@code2024
      POSTGRES_DB: consulat
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: