version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: jondohPostgres
    environment:
      POSTGRES_USER: jondoh
      POSTGRES_PASSWORD: jondohPassword
      POSTGRES_DB: jondohdb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
